// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAImAdBbyuwAI_NdHWpwG_c86KzGC9kHk',
    appId: '1:899923775025:web:de13aeeaf9ce3e6f33cf10',
    messagingSenderId: '899923775025',
    projectId: 'testing-100b2',
    authDomain: 'testing-100b2.firebaseapp.com',
    storageBucket: 'testing-100b2.appspot.com',
    measurementId: 'G-8KXKQTSD8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB61NhGxcSchFHb93WEXQfoGTp2Pe3PJzg',
    appId: '1:899923775025:android:49a37318c3053cd633cf10',
    messagingSenderId: '899923775025',
    projectId: 'testing-100b2',
    storageBucket: 'testing-100b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACBvco8Ombf2CDLH5kLCmIHRK8qxC2F0Q',
    appId: '1:899923775025:ios:ed03995e13c59bfe33cf10',
    messagingSenderId: '899923775025',
    projectId: 'testing-100b2',
    storageBucket: 'testing-100b2.appspot.com',
    iosClientId: '899923775025-406001jvhg6u3a02a15jsrvi8vl6hb3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenmoneyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACBvco8Ombf2CDLH5kLCmIHRK8qxC2F0Q',
    appId: '1:899923775025:ios:a87a8a0fae219e9e33cf10',
    messagingSenderId: '899923775025',
    projectId: 'testing-100b2',
    storageBucket: 'testing-100b2.appspot.com',
    iosClientId: '899923775025-6lajsr2l95aeqrejacv159bubtoo9odf.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenmoneyClone.RunnerTests',
  );
}
